// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AquaBackend.Migrations
{
    [DbContext(typeof(AquaBackendContext))]
    [Migration("20200327184434_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AquaBackend.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrincipalCurrencyCode1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrincipalCurrencyCode2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<string>("SecTypeCode1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecTypeCode2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SettleDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Symbol1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TradeAmount")
                        .HasColumnType("real");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TranCodeLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
